### ISSUE TITLE
Bot doesn't work

### ISSUE THREAD

**Issue by ryanzwe** [tmein/frosty-discord-bot#3]
![image](https://github.com/tmein/frosty-discord-bot/assets/10244230/30695af8-c829-47c5-b17e-687dd0f36af3)

Fix bot

**Comment by tmein** [comment]
![image](https://github.com/tmein/frosty-discord-bot/assets/29010365/1bdf9551-5a6f-43a2-bb4d-bcbaea996016)
Works on my machine.
