### ISSUE TITLE
ANIMA CORE ARMOUR IS BEING IDENTIFIED AS WEAPONS

### ISSUE THREAD

**Issue by ryanzwe** [tmein/frosty-discord-bot#7]
BOT COUNTS ARMOUR AS WEAPONS, YET SHIELDS AREN'T ARMOUR?? YAGEX PLEASE FIX

![image](https://github.com/tmein/frosty-discord-bot/assets/10244230/d2e24155-6165-4bb7-ae66-de4493ea9274)

**Comment by ryanzwe** [comment]
Any updates?

**Comment by tmein** [comment]
User error.
